# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def even_fibs_sum
  fibs = [1,2]
  # construct fibs array
  until fibs[-1] > 4_000_000
    new_fib = fibs[-1] + fibs[-2]
    fibs << new_fib
  end
  # sum up evens
  even_fibs = fibs.select { |fib| fib.even? }
  puts even_fibs
  even_fibs.inject(0) { |accum, fib| accum += fib }
end

# 4613732